name: Test model performance

on:
  pull_request:
    branches: [ main ]

jobs:
  compare-values:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          CURR=`cat version`
          NEW=`cat model_storage/current`
          [[ $NEW > ${CURR:0} ]] && exit 0
          
          RES=`cargo run --quiet --release --bin=evaluation-test`
          PREV=`cat accuracy`
          [[ $RES > ${PREV:0} ]] && (echo $RES > accuracy) && (echo $NEW > version) || exit 1
      - uses: actions/upload-artifact@v4
        with:
          name: accuracy
          path: accuracy
      - uses: actions/upload-artifact@v4
        with:
          name: version
          path: version
